apps/learn/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^article/(?P<id>\d+)$', views.article, name='article')
]

penguin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles import views
import os
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.shop.urls', namespace='shop')),
    url(r'^learn/', include('apps.learn.urls', namespace='learn')),
    url(r'^blog/', include('apps.blog.urls', namespace='blog')),
    url(r'^summernote/', include('django_summernote.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'apps.shop.views.not_found'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/learn/models.py
from __future__ import unicode_literals
from django.db import models

from adminsortable.models import SortableMixin, SortableForeignKey


# Create your models here.
class Category(SortableMixin):
    class Meta:
        verbose_name_plural = "Categories"
        ordering = ['order_for_cat']
    def __unicode__(self):
        return self.name
    name = models.CharField(max_length=255)
    order_for_cat = models.PositiveIntegerField(default=0, editable=False, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Article(SortableMixin):
    class Meta:
        ordering = ['order_for_art']
    def __unicode__(self):
        return self.headline
    headline = models.CharField(max_length=255)
    text = models.TextField(max_length=75000)
    category = SortableForeignKey(Category)
    order_for_art = models.PositiveIntegerField(default=0, editable=False, db_index=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/learn/views.py
from django.shortcuts import render
from .models import Category, Article
from django.db import connection
from django.db.models import Prefetch


def index(request):
    try:
        article = Article.objects.latest("created_at")
    except Article.DoesNotExist:
        article = None
    context = {
        "article": article,
        "all_articles": article_list(),
    }
    return render(request, 'learn/index.html', context)

def article(request,id):
    context = {
        "article": Article.objects.get(id=id),
        "all_articles": article_list(),
    }
    return render(request, 'learn/index.html', context)

################# HELPER FUNCTIONS #################

def article_list(): 
    articles = Article.objects.values('category__name', 'headline', 'id').order_by('category', 'order_for_art')
    return articles

apps/learn/templates/learn/index.html
{% extends 'base.html' %}
  {% block sidebar %}
    {% include 'learn/sidebar.html' %}
  {% endblock %}
  {% block content %}
    <div class="wrapper" id="article" data-id="{{article.id}}">
      {% if not article %}
        <h5 class="center headline">There are no articles currently, check back soon!</h5>
      {% else %}
      <h3 class="ui center aligned header">{{article.headline}}</h3>
      {{article.text|safe}}
      {% endif %}
    </div>
  {% endblock %}

apps/learn/templates/learn/sidebar.html
{% regroup all_articles by category__name as article_list %}
<ul class="side-nav fixed sn">
{% for category in article_list %}
    <li>
        <a href="#" class="subheader grey darken-3 yellow-text text-accent-4">{{category.grouper}}</a>
    </li>
    <li class="divider"></li>
    {% for article in category.list %}
    <li class="text-grey darken-2 article-item" data-id="{{article.id}}">
        <a class="truncate" href="{% url 'learn:article' article.id %}">{{article.headline}}</a>
    </li>
    {% endfor %}
{% endfor %}
</ul>