apps/shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^vacation$', views.vacation_index, name='vacation'),
    url(r'^main$', views.main_index, name='main'),
    url(r'^show/product/(?P<id>\d+)$', views.products.product, name='show_product'),
    url(r'^add/cart/(?P<product_id>\d+)$', views.add_cart, name='add_to_cart'),
    url(r'^show/cart$', views.show_cart, name='show_cart'),
    url(r'^remove/cart/(?P<product_id>\d+)$', views.remove_cart, name='remove_from_cart'),
    url(r'^checkout$', views.checkout, name='checkout'),
    url(r'^news$', views.news, name='news'),
    url(r'^filter$', views.search, name='filter'),
    url(r'^cart_total$', views.get_cart_total, name="cart_total"),
    url(r'^create/order$', views.order_handler, name="order_handler"),
    url(r'^capture/order$', views.capture_paypal, name="payment_capture"),
    url(r'^shipping$', views.shipping, name='shipping'),
    url(r'^payments$', views.payments, name='payments'),
]

penguin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles import views
import os
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.shop.urls', namespace='shop')),
    url(r'^learn/', include('apps.learn.urls', namespace='learn')),
    url(r'^blog/', include('apps.blog.urls', namespace='blog')),
    url(r'^summernote/', include('django_summernote.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'apps.shop.views.not_found'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/shop/models.py
from __future__ import unicode_literals
import StringIO
from datetime import (datetime, timedelta)
import attr

import boto3
from sorl.thumbnail import ImageField, get_thumbnail
import django_countries.fields as countries
import phonenumber_field.modelfields as phonenumber

from django.db import models, transaction
from django.contrib import admin
from django.contrib.contenttypes.fields import GenericForeignKey, GenericRelation
from django.contrib.contenttypes.models import ContentType
from django.utils.safestring import mark_safe
from django.core.files.base import ContentFile
from django.core.files.storage import default_storage as storage
from django.core.files.uploadedfile import SimpleUploadedFile, InMemoryUploadedFile
from django.core.validators import MinValueValidator, MaxValueValidator
from django.core.exceptions import ValidationError
from django.core.cache import cache
from django.utils.translation import ugettext_lazy as _
from fixtures import SHIPPING_OPTIONS

from penguin.settings import THUMB_SIZE, AWS_STORAGE_BUCKET_NAME, AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY

session = boto3.session.Session(aws_access_key_id=AWS_ACCESS_KEY_ID,aws_secret_access_key=AWS_SECRET_ACCESS_KEY)
s3 = session.resource('s3')

SOLD_CHOICES = (
    ('S','Sold'),
    ('A','For Sale'),
    ('P', 'Pending'),
    ('O', 'On Sale'),
    ('C','Collection'),
)

CONDITIONS = (
    ('mint', 'mint'),
    ('near_mint', 'near mint'),
    ('excellent_plus', 'excellent +'),
    ('excellent', 'excellent'),
    ('very_good_plus', 'very good +'),
    ('very_good', 'very good'),
    ('good', 'good'),
    ('fair', 'fair'),
    ('poor', 'poor'),
)

ORDER_STATUS = (
    ('pending', 'Pending'),
    ('ready', 'Ready to Ship'),
    ('shipped', 'Shipped'),
    ('delivered', 'Delivered'),
    ('confirmed', 'Confirmed')
)

ORDER_METHOD = (
    ('paypal', 'PayPal'),
    ('card', 'Credit Card')
)

CARRIER_CHOICES = (
    ("usps", "USPS"),
    ("fedex", "FedEx"),
)

LOCALES = (
    ('US', 'United States of America'),
    ('CA', 'Canada'),
    ('INTER', 'International')
)

SERVICE_TYPES = (
    ('flat_rate', 'Flat Rate'),
    ('express', 'Express')
)

ORDER_SIZE_CAT = (
    ('lte5', '5 or fewer'),
    ('gt5', 'more than 5')
)

def validate_year(value):
    now = datetime.now()
    thisYear = now.year
    if value < 1800 or value > thisYear:
        raise ValidationError(
            _('%(value)s is outside of the range 1800 to %(year)s'),
            params={'value': value,'year':thisYear},
        )


class OrderManager(models.Manager):
    def update_sold_items(self,items): # this sucks
        with transaction.atomic():
            for item in items:
                if item.in_stock > 1:
                    # if we have multiple of this item available, here we duplicate the item and add it to the database, while marking the original item as sold with quantity 0. hacky
                    pen = getattr(item, 'pen', None)
                    knife = getattr(item, 'knife', None)
                    images = item.image.all()
                    item.pk = None
                    item.in_stock -= 1
                    item.status = 'A'
                    item.order = None
                    item.sold_date = None
                    item.save()
                    if pen:
                        # pen must be duplicated bc one to one relationship 
                        pen.pk = None
                        pen.product = item
                        pen.save()
                        item.pen = pen
                    elif knife:
                        # as with pen
                        knife.pk = None
                        knife.product = item
                        knife.save()
                        item.knife = knife
                    for image in images:
                        # images must be duplicated, as with pen
                        image.pk = None
                        image.product = item
                        image.save()
            current_date = datetime.now().date()
            items.update(status='S', sold_date=current_date, in_stock=0)


class Sale(models.Model):

    def __unicode__(self):
        return self.headline

    headline = models.TextField(max_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Address(models.Model):

    def __unicode__(self):
        return "{} \n{} {} \n{}, {} {} \n{}".format(
            self.addressee,
            self.street,
            self.apt,
            self.city,
            self.state,
            self.zip_code,
            self.country
        )

    addressee = models.CharField(max_length=255)
    street = models.CharField(max_length=255)
    apt = models.CharField(max_length=12, null=True, blank=True)
    city = models.CharField(max_length=255)
    state = models.CharField(max_length=255)
    zip_code = models.CharField(max_length=12)
    country = countries.CountryField(blank_label="Select Country")
    phone = phonenumber.PhoneNumberField(null=True, blank=True)
    email = models.EmailField(max_length=254)


class Order(models.Model):

    def __unicode__(self):
        return "{} order for\n{}\nStatus: {}\nSubtotal: ${}\nShipping: ${}".format(
            self.order_method.title(),
            self.shipping_address,
            self.status,
            self.subtotal,
            self.shipping
        )

    order_method = models.CharField(max_length=10, choices=ORDER_METHOD)
    order_id = models.CharField(max_length=255, blank=True, null=True)
    subtotal = models.DecimalField(max_digits=8,decimal_places=2,validators=[MinValueValidator(0.01)])
    shipping = models.DecimalField(max_digits=8,decimal_places=2,validators=[MinValueValidator(0.01)])
    shipping_address = models.ForeignKey(Address, on_delete=models.CASCADE, related_name="order")
    shipping_carrier = models.CharField(max_length=25, choices=CARRIER_CHOICES)
    shipping_service = models.CharField(max_length=55, choices=SERVICE_TYPES)
    status = models.CharField(max_length=10,choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = OrderManager()


class Product(models.Model):

    def __unicode__(self):
        return "{} {}".format(self.make, self.model)

    make = models.CharField(max_length=55)
    model = models.CharField(max_length=55)
    condition = models.CharField(max_length=25,choices=CONDITIONS)
    flaws = models.CharField(max_length=100)
    special_shipping = models.BooleanField("This item requires special packaging. It will not fit into a USPS flat rate box or FedEx envelope.")
    length = models.DecimalField("Length in inches", max_digits=5,decimal_places=1,validators=[MinValueValidator(0.1)], default=5.0)
    width = models.DecimalField("Width in inches", max_digits=5,decimal_places=1, validators=[MinValueValidator(0.1)], default=1.0, help_text="Please modify width default only if item to be shipped is not a single pen.")
    depth = models.DecimalField("Depth in inches", max_digits=5,decimal_places=1, validators=[MinValueValidator(0.1)], default=1.0, help_text="Please modify depth default only if item to be shipped is not a single pen.")
    weight = models.DecimalField("Weight in ounces", max_digits=5,decimal_places=1,default=3.0,validators=[MinValueValidator(0.1)])
    price = models.DecimalField(max_digits=8,decimal_places=2,validators=[MinValueValidator(0.01)])
    description = models.TextField(max_length=2000)
    purchase_source = models.CharField(max_length=55)
    purchase_date = models.DateField()
    cost = models.DecimalField(max_digits=8,decimal_places=2,validators=[MinValueValidator(0.01)], help_text="If number in stock is more than 1 enter average purchase cost")
    status = models.CharField(max_length=1,choices=SOLD_CHOICES,default='A')
    in_stock = models.IntegerField(default=1, validators=[MinValueValidator(0)], help_text="If number is 0 product must be marked sold.")
    sold_date = models.DateField(blank=True,null=True)
    sale = models.ForeignKey(Sale, related_name='products', blank=True, null=True, on_delete=models.CASCADE)
    order = models.ForeignKey(Order,related_name='products', blank=True, null=True, on_delete=models.SET_NULL)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Pen(models.Model):
    product = models.OneToOneField(Product, related_name='pen', on_delete=models.CASCADE)
    year = models.IntegerField(validators=[validate_year])
    country = countries.CountryField(blank=True, null=True)
    cap_color = models.CharField(max_length=25)
    body_color = models.CharField(max_length=25)
    nib_description = models.CharField(max_length=55)
    nib_make = models.CharField(max_length=25)
    nib_grade = models.CharField(max_length=25)
    nib_material = models.CharField(max_length=25)
    nib_flexibility = models.CharField(max_length=25)
    nib_alternative = models.BooleanField()


class Knife(models.Model):
    class Meta:
        verbose_name_plural = "knives"

    product = models.OneToOneField(Product, related_name='knife', on_delete=models.CASCADE)
    knife_type = models.CharField(max_length=25)
    blade_material = models.CharField(max_length=25)
    handle_material = models.CharField(max_length=25)
    blade_length = models.DecimalField(max_digits=4,decimal_places=2)


class Image(models.Model):

    def __unicode__(self):
        return "Image for: {}".format(self.product)

    product = models.ForeignKey(Product, related_name='image', blank=True, null=True, on_delete=models.CASCADE)
    image = ImageField(null=True, upload_to='images')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Bulletin(models.Model):

    def __unicode__(self):
        return "{}".format(self.headline)

    headline = models.CharField(max_length=155)

apps/shop/views/cart.py
import attr
from django.shortcuts import redirect, render
from django.urls import reverse
from django.http import JsonResponse

from ..cart import Cart


def add_cart(request, product_id):
    '''
    view method to add an item to user's cart
    '''
    cart = Cart(request)
    cart.add(int(product_id))
    return redirect(reverse('shop:show_cart'))

def remove_cart(request, product_id):
    '''
    remove item from shopping cart
    '''
    cart = Cart(request)
    cart.remove([int(product_id)])
    return redirect(reverse('shop:show_cart'))

def get_cart_total(request):
    '''
    view method to get total shopping cart items' value
    '''
    cart = Cart(request)
    context = {
        "total_cost": cart.total()
    }
    return JsonResponse(context)


def show_cart(request):
    '''
    get cart contents
    remove any sold items
    render cart
    '''
    cart = Cart(request)
    context = attr.asdict(cart)
    return render(request, 'shop/cart.html', context)

apps/shop/views/index.py
from datetime import (
    datetime,
    timedelta
)

from django.shortcuts import (
    render,
    redirect
)
from django.urls import reverse

from ..models import (
    Bulletin,
    Product,
    VacationSettings
)
from django.core.paginator import Paginator


def index(request):
    vacation_settings = VacationSettings.load()

    if 'cart' not in request.session:
        request.session['cart'] = []

    if vacation_settings.active:
        return redirect(reverse('shop:vacation'))
    else:
        return redirect(reverse('shop:main'))


def vacation_index(request):
    return render(request, 'shop/temp_index.html')


def main_index(request):
    today = datetime.now()
    month_ago = today - timedelta(days=int(30))
    all_products = Product.objects.filter(status='A').order_by('-created_at').prefetch_related('pen').prefetch_related('image')
    paginator = Paginator(all_products, 24)
    products = paginator.page(1)
    context = {
        'products': products,
        'bulletins': Bulletin.objects.filter(updated_at__range=(month_ago, today), active=True).order_by('-updated_at')[:1]
    }

    return render(request, 'shop/index.html', context)


def news(request):
    bulletins = Bulletin.objects.filter(active=True).order_by('-updated_at')
    context = {
        "bulletins": bulletins,
    }
    return render(request, 'shop/news.html', context)


def not_found(request):
    return render(request, 'shop/404.html')

apps/shop/templates/shop/cart.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block sidebar %}
  {% include 'shop/sidebar.html' %}
{% endblock %}
{% block content %}
<div class="wrapper" id="store">
  <h3 class="header center">Your Cart:</h3>
  {% if sold_items %}
    <div class="sold-items-err">
      <i class="fa fa-exclamation-triangle fa-2x err-circle" aria-hidden="true"></i>
      You waited too long! The following items were sold:
      {% for item in sold_items %}
      {{item}}
      {% endfor %}
    </div>
  {% endif %}
  {% if not items %}
  <div class="row">
    <h5 class="center red-text text-darken-2">There's nothing in your cart!</h5>
  </div>
  {% else %}
  <div class="row">
    <div class="col s12">
      <div class="card-panel card-warning">
        <p>Our online checkout is temporarily unavailable. Sorry for the inconvenience. To order please contact Rick at
        <a href="mailto:rickpropas@comcast.net">rickpropas@comcast.net</a></p>
      </div>
    </div>
  </div>
    {% for item in items %}
    <div class="row">
      <ul class="collection">
        <li class="collection-item">
          {% thumbnail item.image.all.0.image "120" as im %}
          <a class="col s2" href="{% url 'shop:show_product' item.id %}"><img src="{{im.url}}" class="cart-thumb" alt="image for {{item}}"></a>
          {% endthumbnail %}
          <p class="col s7 cart-text">{{item}}</p>
          <a class="col s1 cart-text grey-text" id="cart-delete" href="{% url 'shop:remove_from_cart' item.id %}">
            <i class="fa fa-trash" aria-hidden="true"></i>
          </a>
          <p class="col s2 cart-text cart-price">${{item.price}}</p>
        </li>
      </ul>
    </div>
    {% endfor %}
    <div class="row rt">
      <p class="emphasis-small">Item Subtotal: ${{total}}</p>
    </div>
    {% if vacation_settings.active %}
    <div class="row right-align">
      <p class="warning">Please remember that items will not ship until the week of {{vacation_settings.end_date|date:"F dS, Y"}}</p>
    </div>
    {% endif %}
    <div class="row rt">
      <!-- <a href="{% url 'shop:checkout' %}"> -->
        <button class="btn yellow accent-4 grey-text text-darken-3" type="button" disabled>Checkout</button>
      <!-- </a> -->
    </div>
    {% endif %}
  </div>
{% endblock %}

apps/shop/templates/shop/error_email.html
{% load shop_extras %} {% load thumbnail %} {% load static %}
<!DOCTYPE html> {% load shop_extras %} {% load thumbnail %} {% load static %}
<html lang="en" style="padding: 0;margin: 0;font-family: 'Roboto', 'Verdana', 'sans-serif';">

<head style="padding: 0;margin: 0;font-family: 'Roboto', 'Verdana', 'sans-serif';">
</head>

<body style="padding: 0;margin: 0;font-family: 'Roboto', 'Verdana', 'sans-serif';">

    <div class="wrapper" style="padding: 0;margin: 0 auto;font-family: 'Roboto', 'Verdana', 'sans-serif';width: 80%;">
        <div class="header" style="padding: 10px 20px;margin: 0;font-family: 'Lobster Two', 'Arial Narrow', Arial, sans-serif;width: 100%;font-size: 2em;color: #fff;background-color: #424242;">
            the
            <span class="yellow" style="padding: 0;margin: 0;font-family: 'Lobster Two', 'Arial Narrow', Arial, sans-serif;color: #ffd600;">pen</span>guin
        </div>
        <div class="blurb" style="padding: 20px;margin: 0 auto;font-family: 'Roboto', 'Verdana', 'sans-serif';width: 80%;line-height: 1.5em;">
            <div style="padding: 0;margin: 20px 0;font-family: 'Roboto', 'Verdana', 'sans-serif';">
                <p>
                    <span style="color: #d84315; font-weight: bold;"> WARNING! </span>Something went wrong when e-mailing the
                    customer.
                </p>
                <p>This means either:
                    <ol>
                        <li>there is an error in your service</li>
                        <li>the client email was not valid</li>
                        <li>there was an error in the mailgun service</li>
                    </ol>
                </p>
                <p>Below is the client's information. Please attempt to contact them via email or phone, or they will not be notified. You will also receive the standard sales e-mail shortly with further order details.</p>
                <p>e-mail: 
                    <a href="mailto:{{order.shipping_address.email}}" style="padding: 0;margin: 0;font-family: 'Roboto', 'Verdana', 'sans-serif';text-decoration: none;color: #0288d1;">
                        {{order.shipping_address.email}}
                    </a>
                </p>
                <p>phone: <a href="tel:{{order.shipping_address.phone}}" style="padding: 0;margin: 0;font-family: 'Roboto', 'Verdana', 'sans-serif';text-decoration: none;color: #0288d1;">{{order.shipping_address.phone}}</a></p>
            </div>
        <p>Items in order:</p>
        <ul style="padding: 0;margin: 0;font-family: 'Roboto', 'Verdana', 'sans-serif';margin-bottom: 20px;">
            {% for item in order.products.all %}
            <li style="padding: 0;margin: 0;font-family: 'Roboto', 'Verdana', 'sans-serif';">item id#: {{item.id}}, item
                description: {{item}} {% endfor %}
            </li>
        </ul>
        </div>
        <h2 style="padding: 0;margin: 0;font-family: 'Roboto', 'Verdana', 'sans-serif';text-align: center;">Order Summary</h2>
        <div class="row order-summary" style="padding: 0;margin: 20px auto;font-family: 'Roboto', 'Verdana', 'sans-serif';border: 1px solid #eeeeee;width: 90%;">
            <div class="col s6 order" style="padding: 20px;margin: 0;font-family: 'Roboto', 'Verdana', 'sans-serif';border-right: 1px solid #eeeeee;width: 50%;display: inline-block;vertical-align: top;box-sizing: border-box;">
                <h5 style="padding: 0;margin: 0;font-family: 'Roboto', 'Verdana', 'sans-serif';font-size: 1.2em;font-weight: bold;">Order:</h5>
                <p style="padding: 0;margin: 0;font-family: 'Roboto', 'Verdana', 'sans-serif';">Order #: {{order.id}}</p>
                <p style="padding: 0;margin: 0;font-family: 'Roboto', 'Verdana', 'sans-serif';">Order total: ${{order.subtotal|add_float:order.shipping}}</p>
                <p style="padding: 0;margin: 0;font-family: 'Roboto', 'Verdana', 'sans-serif';">Shipping carrier: {{order.get_shipping_carrier_display}}</p>
                <p style="padding: 0;margin: 0;font-family: 'Roboto', 'Verdana', 'sans-serif';">Shipping service: {{order.get_shipping_service_display}}</p>
            </div>
            <div class="col s6 address" style="padding: 20px;margin: 0;font-family: 'Roboto', 'Verdana', 'sans-serif';display: inline-block;vertical-align: top;box-sizing: border-box;">
                <h5 style="padding: 0;margin: 0;font-family: 'Roboto', 'Verdana', 'sans-serif';font-size: 1.2em;font-weight: bold;">Address:</h5>
                {{order.shipping_address|linebreaksbr}}
            </div>
        </div>
        <div class="footer" style="padding: 10px 20px;margin: 0;font-family: 'Lobster Two', 'Arial Narrow', Arial, sans-serif;width: 100%;font-size: 2em;color: #fff;background-color: #424242;height: 1.6em;"></div>
    </div>
</body>

</html>

apps/shop/templates/shop/index.html
{% extends 'base.html' %}
{% load shop_extras %}
{% load thumbnail %}
{% block sidebar %}
{% include 'shop/sidebar.html' %}
{% endblock %}
  {% block content %}
    <div class="wrapper">
      <h3 class="ui center aligned header headline">News</h3>
      {% for bulletin in bulletins %}
      <div class="row">
        <div class="col s12 m12">
          <div class="card-panel card-yellow white">
            <h3 class="grey lighten-3 bulletin-head">{{bulletin.headline}}</h3>
            <div class="bulletin-body">
               {{bulletin.text|safe|truncatechars_html:550}}
              {% if bulletin.text|is_trunc:550 %}
              <button type="button" class="btn waves-effect waves-gray btn-flat modal-trigger" id="{{bulletin.id}}">read more</button>
              {% endif %}
            </div>
          </div>
        </div>
      </div>
      <!-- Modal for each bulletin -->
      <div id="modal{{bulletin.id}}" class="modal">
        <div class="modal-content">
          <h5 class="modal-head grey lighten-3">
            {{bulletin.headline}}
            <i class="fa fa-window-close-o closer" aria-hidden="true"></i>
          </h5>
          <div class="modal-body">
            {{bulletin.text|safe}}
          </div>
          
        </div>
      </div>
      {% endfor %}
      <a href="{% url 'shop:news' %}"><button class="waves-effect waves-light yellow accent-4 btn news-btn grey-text text-darken-3">see all news</button></a>
      <div class="divider"></div>
      <h3 class="ui center aligned header headline">Recently Added {{products.count}}</h3>
      <div class="row" id="main">
       {% for item in products %}
      <div class="col s3 magic">
        <a href="{% url 'shop:show_product' item.id %}">
          <div class="card hoverable">
            <div class="card-image">
              {% thumbnail item.image.all.0.image 'x250' as im %}
              <img src="{{im.url}}" alt="image for {{item}}" class="product-thumbs"> {% endthumbnail %}
            </div>
            <div class="card-content">
              <p class="truncate">{{item}}</p>
              <p>${{item.price}}</p>
            </div>
          </div>
        </a>
      </div>
      {% endfor %}
      </div>
      {% if products.has_next %}
      <a href="{% url 'shop:filter' %}?filter=recent&value=30&page=2">
        <button type="button" class="waves-effect waves-light yellow accent-4 btn news-btn grey-text text-darken-3">See more recently added products</button>
      </a>
      {% endif %}
    </div>
  {% endblock %}

apps/shop/templates/shop/products.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block sidebar %}
{% include 'shop/sidebar.html' %}
{% endblock %}
{% block content %}
<div class="wrapper" id="store">
    <h3 class="center headline">{{headline}}</h3>
    <div class="row" id="main">
        {% for item in products %}
        <div class="col s3 magic">
            <a href="{% url 'shop:show_product' item.id %}">
                <div class="card hoverable">
                    <div class="card-image">
                        {% thumbnail item.image.all.0.image 'x250' as im %}
                        <img src="{{im.url}}" alt="image for {{item}}" class="product-thumbs"> {% endthumbnail %}
                    </div>
                    <div class="card-content">
                        <p class="truncate">{{item}}</p>
                        <p>${{item.price}}</p>
                    </div>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
    <div class="row">
        <div class="col s4 left-align">
            {% if products.has_previous %}
            <a href="{% url 'shop:filter' %}?filter={{filter}}&value={{value}}&page={{ products.previous_page_number }}" class="grey-text text-darken-3 waves-effect waves-light nav-arrows">
                <i class="fa fa-chevron-left" aria-hidden="true"></i> PREVIOUS
            </a>
            {% endif %}
        </div>
        {% if products %}
        <div class="col s4 nav-pages center-align">
            Page {{ products.number }} of {{ products.paginator.num_pages }}
        </div>
        {% endif %}
        <div class="col s4 right-align">
            {% if products.has_next %}
            <a href="{% url 'shop:filter' %}?filter={{filter}}&value={{value}}&page={{products.next_page_number}}" class="grey-text text-darken-3 waves-effect waves-light nav-arrows">
                NEXT <i class="fa fa-chevron-right" aria-hidden="true"></i>
            </a>
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

apps/shop/templates/shop/success.html
{% load shop_extras %}
{% load thumbnail %} 
{% load static %}
<div class="success-container">
    <div class="center">
        <i class="fa fa-check-circle fa-4x light-green-text text-darken-1" aria-hidden="true"></i>
        <h3 class="light-green-text text-darken-1 success-msg">We got your order!</h3>
    </div>
    {% if vacation_settings.active %}
    <div class="center warning">
        <p>Please keep in mind that we are on vacation for the next {{delay_weeks}} weeks.</p>
        <p>Your order will not be shipped until the week of {{vacation_settings.end_date}}.</p>
    </div>
    {% endif %}
    <h4 class="center">Order Summary:</h4>
    <div class="row order-summary">
        <div class="col s6 order">
            <h5>Order:</h5>
            <p>Order #: {{order.id}}</p>
            <p>Order total: ${{order.subtotal|add_float:order.shipping}}</p>
            <p>Shipping carrier: {{order.get_shipping_carrier_display}}</p>
            <p>Shipping service: {{order.get_shipping_service_display}}</p>
        </div>
        <div class="col s6 address">
            <h5>Address:</h5>
            {{order.shipping_address|linebreaksbr}}
        </div>
    </div>
    <div class="order-review-cont">
        {% for product in order.products.all %}
            <div class="row">
                {% thumbnail product.image.all.0.image "x50" as im %}
                <div class="col s2">
                    <img src="{{im.url}}" class="main-product-image" width={{im.width}} height={{im.height}}>     
                </div>
                {% endthumbnail %}
                <span class="col s8">
                    {{product}}
                </span> 
                <span class="col s2 right-align">
                    ${{product.price}}
                </span>
            </div>
        {% endfor %}
    </div>
    <div class="center">
        <p>If there's something wrong with the above and you need to contact us, or if you just want to talk, find us at <a href="mailto:rickpropas@comcast.net">rickpropas@comcast.net</a></p>
        <a href="{% url 'shop:index' %}">
            <button class="btn yellow accent-4" type="button">Continue Shopping</button>
        </a>
    </div>

</div>