apps/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^show/blog/(?P<id>\d+)$', views.index, name="blog")
]

penguin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles import views
import os
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.shop.urls', namespace='shop')),
    url(r'^learn/', include('apps.learn.urls', namespace='learn')),
    url(r'^blog/', include('apps.blog.urls', namespace='blog')),
    url(r'^summernote/', include('django_summernote.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'apps.shop.views.not_found'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

apps/blog/models.py
from __future__ import unicode_literals
from django.db import models

# Create your models here.
class Post(models.Model):
    def __unicode__(self):
        return self.title
    title = models.CharField(max_length=255)
    text = models.TextField(max_length=75000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

apps/blog/views.py
from django.shortcuts import render
from .models import Post

def index(request, id=-1):
    if id < 0:
        try:
            post = Post.objects.latest('updated_at')
        except Post.DoesNotExist:
            post = None
    else:
        post = Post.objects.get(id=id)
    if post:
        post_length = len(post.text)
        slice_length = post_length if post_length < 550 else 550
    else:
        slice_length = 0
    context = {
        'post': post,
        'slice_length':  slice_length,
        'recent_blogs': blog_list(),
    }
    return render(request, 'blog/index.html', context)


def blog(request,id):
    post = Post.objects.get(id=id)
    context = {
        'post': post,
    }
    return render(request, 'blog/index.html', context)

################ HELPER FUNCTIONS ################

def blog_list():
    blogs = Post.objects.all().order_by("-updated_at")
    return blogs

apps/blog/templates/blog/index.html
{% extends 'base.html' %} 
{% block sidebar %} 
{% include 'blog/sidebar.html' %} 
{% endblock %} 
{% block content %} 
{% load tz %}
<div class="wrapper" id="blog" data-id="{{post.id}}">
    {% if not post %}
        <h5 class="center headline">There are no blog posts currently, check back soon!</h5>
    {% endif %} 
    {% if post %}
        <h4 class="ui center aligned header headline">{{post}}</h4>
        <p class="date-stamp grey-text text-lighten-1 center-align">Last Updated: {{post.updated_at|date:"F j, Y"}} at {{post.updated_at|time:"g:i a"}}</p>
        {{post.text|safe}}
    {% endif %} 
</div>
{% endblock %}

apps/blog/templates/blog/sidebar.html
<ul class="side-nav fixed sn">
  {% for blog in recent_blogs %}
  <li id="blog-item">
    <a href="{% url 'blog:blog' blog.id %}" class="blog-item" id="link-wrapper" data-id="{{blog.id}}">
      <div class="blog-title truncate" id="title">{{blog}}</div>
      <div class="blog-stamp grey-text" id="date">{{blog.updated_at|date:"F jS, Y"}}</div>
    </a>
  </li>
  {% endfor %}
</ul>