apps/blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^show/blog/(?P<id>\d+)$', views.index, name="blog")
]

apps/shop/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^vacation$', views.vacation_index, name='vacation'),
    url(r'^main$', views.main_index, name='main'),
    url(r'^show/product/(?P<id>\d+)$', views.products.product, name='show_product'),
    url(r'^add/cart/(?P<product_id>\d+)$', views.add_cart, name='add_to_cart'),
    url(r'^show/cart$', views.show_cart, name='show_cart'),
    url(r'^remove/cart/(?P<product_id>\d+)$', views.remove_cart, name='remove_from_cart'),
    url(r'^checkout$', views.checkout, name='checkout'),
    url(r'^news$', views.news, name='news'),
    url(r'^filter$', views.search, name='filter'),
    url(r'^cart_total$', views.get_cart_total, name="cart_total"),
    url(r'^create/order$', views.order_handler, name="order_handler"),
    url(r'^capture/order$', views.capture_paypal, name="payment_capture"),
    url(r'^shipping$', views.shipping, name='shipping'),
    url(r'^payments$', views.payments, name='payments'),
]

penguin/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.contrib.staticfiles import views
import os
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('apps.shop.urls', namespace='shop')),
    url(r'^learn/', include('apps.learn.urls', namespace='learn')),
    url(r'^blog/', include('apps.blog.urls', namespace='blog')),
    url(r'^summernote/', include('django_summernote.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler404 = 'apps.shop.views.not_found'

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <title>The Penguin</title>
    {% load static %}
    <link href="https://fonts.googleapis.com/css?family=Lobster+Two" rel="stylesheet">
    <link type="text/css" rel="stylesheet" href="{% static 'materialize/css/materialize.min.css' %}"  media="screen,projection"/>
    <script type="text/javascript" src="{% static 'js/jquery-3.1.1.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/main.js' %}"></script>
    <link type="text/css" rel="stylesheet" href="{% static 'slick/slick.css' %}" media="screen,projection"/>
    <link type="text/css" rel="stylesheet" href="{% static 'slick/slick-theme.css' %}" media="screen,projection" />
    <link rel="icon" type="image/png" href="{% static 'imgs/penguin-favicon.png' %}" />
    <link rel="stylesheet" href="{% static 'css/penguin.css' %}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>
  <body>
    <!-- preloader for checkout must be in base to overlay all elements -->
    <div id="ovl" class="loading-overlay"></div>
    <div id="preloader" class="preloader">
      <div class="load-icon">
        <i class="fas fa-pen-nib fa-3x fa-pulse"></i>
      </div>
      <p>We are processing your payment information...</p>
    </div>
    {% block navbar %}
    {% include 'navbar.html' %}
    {% endblock %}
    {% block sidebar %}{% endblock %}
    {% block content %}{% endblock %}
    {% block footer %}
    {% include 'footer.html' %}
    {% endblock %}
    <script type="text/javascript" src="{% static 'materialize/js/materialize.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'slick/slick.min.js' %}"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.7.0/js/all.js" integrity="sha384-qD/MNBVMm3hVYCbRTSOW130+CWeRIKbpot9/gR1BHkd7sIct4QKhT1hOPd+2hO8K" crossorigin="anonymous"></script>
  </body>
  </html>
  

templates/footer.html
<footer class="page-footer grey darken-3 grey-text text-lighten-4">
    <div class="container">
    <div class="row">
        <div class="col s4 section">
            <p class="section-header">Contact</p>
            <p><a href="mailto:rickpropas@comcast.net"> rickpropas@comcast.net</a></p>
            <p><a href="tel:1-510-754-3278">+1 510 754 3278</a></p>
        </div>
        <div class="col s4 section">
            <p class="section-header">Navigation</p>
            <p><a href="{% url 'shop:index'%}">Shop</a></p>
            <p><a href="{% url 'learn:index'%}">Learn</a></p>
            <p><a href="{% url 'blog:index'%}">Blog</a></p>
            <p><a href="/learn/article/8">About Us</a></p>
        </div>
        <div class="col s4 section">
            <p class="section-header">Social</p>
            <p>
                <a href="https://www.facebook.com/The-PENguin-141481862550717/">
                <i class="fab fa-facebook fa-2x" aria-hidden="true"></i>
                </a>
            </p>
            <p>
                <a href="https://www.instagram.com/rickpropas/?hl=en">
                <i class="fab fa-instagram fa-2x" aria-hidden="true"></i>
                </a>
            </p>
            <p>
                <a href="https://twitter.com/rickpropas">
                <i class="fab fa-twitter-square fa-2x" aria-hidden="true"></i>
                </a>
            </p>
        </div>
    </div>
    </div>
    <div class="divider grey darken-2"></div>
    <div class="footer-copyright">
    <div class="container">
        <div class="row">
        <div class="col s6">© 2018 Anna Propas</div>
        <div class=" col s6">
            <span class="right email-footer">contact Anna at <a href="mailto:apropas@gmail.com"> apropas@gmail.com</a></span>
        </div>
        </div>
    </div>
    </div>
</footer>

templates/navbar.html
<div class="navbar-fixed">
  <nav>
    <div class="nav-wrapper grey darken-3">
      <div class="row">
        <div class="col s3">
          <a class="penguin_logo" href="/">the &nbsp;<span class="yellow-text text-accent-4">pen</span>guin</a>
        </div>
        <div class="col s5">
          <form action="{% url 'shop:filter' %}" method="get" id="search-form">
            <div class="input-field col s6 right">
              <input type="hidden" name="filter" value="search">
              <input id="search" type="text" name="value" class="validate">
              <label for="search">
                <i class="fa fa-search" aria-hidden="true"></i>
                Search Products
              </label>
            </div>
          </form>
        </div>
        <div class="col s4">
          <ul id="nav-mobile" class="right nav-list">
            <li class="cart">
              <a href="{% url 'shop:show_cart' %}" class="yellow-text text-accent-4">
                <span class="fa-layers fa-fw fa-2x">
                  <i class="fas fa-shopping-cart" data-fa-transform="grow-1 down-1"></i>
                  <span class="fa-layers-text fa-inverse counter" data-fa-transform="shrink-8 up-1 right-2" style="font-weight:900; color:#424242">{{cart}}</span>
                </span>
              </a>
            </li>
            <li class="shop">
              <a href="{% url 'shop:index'%}">
                shop <span class="pen"><i class="fas fa-pen-fancy" data-fa-transform="grow-1 right-5"></i></span>
              </a>
            </li>
            <li class="learn">
              <a href="{% url 'learn:index'%}">
                learn <span class="glasses"> <i class="fas fa-glasses fa-sm" data-fa-transform="grow-1 right-5"></i></span>
              </a>
            </li>
            <li class="blog">
              <a href="{% url 'blog:index'%}">
                blog <span class="blog-icon"><i class="fas fa-blog" data-fa-transform="grow-1 right-5"></i></span>
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
  </nav>
</div>